# Generated by Django 4.1.5 on 2023-02-15 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='post',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='product',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='like',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='favorites',
            unique_together={('owner', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('owner', 'product')},
        ),
    ]
